<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Profile Panel</h1>
        <p class="col-md-8 fs-4">
            When you are authenticated, the "Go" link will take you to the secure ProfileController, if you are not authenticated, you will be redirected to the login form
        </p>
        <a href="/profile" class="btn btn-primary btn-lg" type="button">Go</a>
    </div>
</div>

<div class="row align-items-md-stretch">
    <div class="col-md-6">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
            <h2>Action Exceptions</h2>
            <p>The "Open" link will open the page, action, in the CustomersController that was excluded from authenticated access</p>
            <a href="/customers/reports" class="btn btn-outline-light" type="button">Open</a>
        </div>
    </div>
    <div class="col-md-6">
        <div class="h-100 p-5 bg-light border rounded-3">
            <h2>-</h2>
            <p>-</p>
            <a class="btn btn-outline-secondary" type="button">-</a>
        </div>
    </div>
</div>


