<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Phalcon PHP Framework</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->getDI()->getShared("url")->get('img/favicon.ico')?>"/>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    </head>
    <body>
    <div class="container ">
        <header class="py-3 mb-4 border-bottom">
            <div class="container d-flex flex-wrap justify-content-center">
                <a href="/" class="d-flex align-items-center mb-3 mb-lg-0 me-lg-auto text-dark text-decoration-none">
                    <img src="https://raw.githubusercontent.com/sinbadxiii/images/master/cphalcon-auth/logo.png" height="50px" />
                    <span class="fs-4 mx-3"> Phalcon Auth Example</span>
                </a>
            </div>

            <div class="container d-flex flex-wrap">
                <ul class="nav me-auto">
                    <li class="nav-item"><a href="/" class="nav-link link-dark px-2">Home</a></li>
                    <li class="nav-item"><a href="#" class="nav-link link-dark px-2">About</a></li>
                    <li class="nav-item"><a href="#" class="nav-link link-dark px-2">Contacts</a></li>
                    <li class="nav-item"><a href="/profile" class="nav-link link-dark px-2">Profile</a></li>
                    <li class="nav-item"><a href="/admin" class="nav-link link-dark px-2">Admin</a></li>
                    <li class="nav-item"><a href="/admin/users" class="nav-link link-dark px-2">Admin Users</a></li>
                </ul>
                <ul class="nav">
                    <?php if ($this->auth->check()):?>
                        <li class="nav-item"><a href="/logout" class="nav-link link-dark px-2">Logout</a></li>
                    <?php else:?>
                        <li class="nav-item"><a href="/login" class="nav-link link-dark px-2">Login</a></li>
                        <li class="nav-item"><a href="/register" class="nav-link link-dark px-2">Sign up</a></li>
                    <?php endif;?>
                </ul>
            </div>
        </header>


        <?php echo $this->getContent(); ?>

        <footer class="pt-3 mt-4 text-muted border-top">
            &copy; <?=date('Y');?> Phalcon Auth Example
        </footer>
    </div>

    </body>
</html>
